// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: proto/exchange.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageExchangeService_SendMessage_FullMethodName    = "/exchange.MessageExchangeService/SendMessage"
	MessageExchangeService_StreamMessages_FullMethodName = "/exchange.MessageExchangeService/StreamMessages"
)

// MessageExchangeServiceClient is the client API for MessageExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageExchangeServiceClient interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageRequest, MessageResponse], error)
}

type messageExchangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageExchangeServiceClient(cc grpc.ClientConnInterface) MessageExchangeServiceClient {
	return &messageExchangeServiceClient{cc}
}

func (c *messageExchangeServiceClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, MessageExchangeService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageExchangeServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageRequest, MessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageExchangeService_ServiceDesc.Streams[0], MessageExchangeService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessageRequest, MessageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageExchangeService_StreamMessagesClient = grpc.BidiStreamingClient[MessageRequest, MessageResponse]

// MessageExchangeServiceServer is the server API for MessageExchangeService service.
// All implementations must embed UnimplementedMessageExchangeServiceServer
// for forward compatibility.
type MessageExchangeServiceServer interface {
	SendMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	StreamMessages(grpc.BidiStreamingServer[MessageRequest, MessageResponse]) error
	mustEmbedUnimplementedMessageExchangeServiceServer()
}

// UnimplementedMessageExchangeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageExchangeServiceServer struct{}

func (UnimplementedMessageExchangeServiceServer) SendMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageExchangeServiceServer) StreamMessages(grpc.BidiStreamingServer[MessageRequest, MessageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedMessageExchangeServiceServer) mustEmbedUnimplementedMessageExchangeServiceServer() {
}
func (UnimplementedMessageExchangeServiceServer) testEmbeddedByValue() {}

// UnsafeMessageExchangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageExchangeServiceServer will
// result in compilation errors.
type UnsafeMessageExchangeServiceServer interface {
	mustEmbedUnimplementedMessageExchangeServiceServer()
}

func RegisterMessageExchangeServiceServer(s grpc.ServiceRegistrar, srv MessageExchangeServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageExchangeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageExchangeService_ServiceDesc, srv)
}

func _MessageExchangeService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageExchangeServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageExchangeService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageExchangeServiceServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageExchangeService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageExchangeServiceServer).StreamMessages(&grpc.GenericServerStream[MessageRequest, MessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageExchangeService_StreamMessagesServer = grpc.BidiStreamingServer[MessageRequest, MessageResponse]

// MessageExchangeService_ServiceDesc is the grpc.ServiceDesc for MessageExchangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageExchangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.MessageExchangeService",
	HandlerType: (*MessageExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageExchangeService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _MessageExchangeService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/exchange.proto",
}
